apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-sc
reclaimPolicy: Retain
volumeBindingMode: Immediate
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vue-filestore-app-p-volume
  labels:
    type: app
spec:
  storageClassName: app-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /apps
    server: 139.224.132.234
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc-claim
spec:
  storageClassName: app-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vue-filestore
  name: vue-filestore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vue-filestore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: vue-filestore
    spec:
      containers:
      - args: ["/sh/init_openresty.sh"]
        env:
        - name: SERVICE_NAME
          value: vue_filestore
        - name: SERVICE_TAGS
          value: vue_filestore,http,80
        image: xjyplayer/simple_filestore_nginx:1.0.1
        imagePullPolicy: IfNotPresent
        name: filestore-nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /apps/vue_file_store_pro
          subPath: vue_file_store_pro
          name: vue-filestore-pvc
        - mountPath: /apps/logs
          subPath: logs
          name: vue-filestore-pvc
        - mountPath: /apps/simple_file_store_nginx
          subPath: simple_file_store_nginx
          name: vue-filestore-pvc
        - mountPath: /usr/local/openresty/nginx/conf/nginx_template.conf
          subPath: conf/nginx/nginx.conf
          name: nginx-conf
        workingDir: /apps/simple_file_store_nginx
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: vue-filestore-pvc
        persistentVolumeClaim:
          claimName: app-pvc-claim
      - name: nginx-conf
        configMap:
          name: filestore-nginx-config-map
          items:
          - key: nginx.conf
            path: conf/nginx/nginx.conf
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vue-filestore
  name: vue-filestore-server
spec:
  ports:
  - name: vue-filestore-server-main-port
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: vue-filestore
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vue-filestore-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: file.52db.club
    http:
      paths:
      - backend:
          serviceName: vue-filestore-server
          servicePort: 80
        path: /
  tls:
   - secretName: filestore-imroc-io-tls
     hosts:
       - file.52db.club


